### ISSUE TITLE
Config table passed to vshard.router.cfg() is destroyed

### ISSUE THREAD

**Issue by racktear** [tarantool/vshard#1]
I tried to launch both router and storage on the same node this way:

```lua
local vshard_cfg = {
    sharding = {
        { -- replicaset #1
            { uri = 'localhost:3301', name = 'storage_1_a', master = true },
        }
    }
}
vshard.router.cfg(vshard_cfg)
vshard.storage.cfg(vshard_cfg, 'storage_1_a')
```

But it fails, because the call to `vshard.router.cfg` destroys the configuration table passed to it.

As a result, I get this:

```sh
./vshard/util.lua:41: Sharding config must be array of replicasets
```

**Comment by Gerold103** [comment]
https://github.com/tarantool/vshard/commit/9a477665f3808fcdff64a00fe9cc029b1f476a44
