### ISSUE TITLE
Can I distribute by range，not the weight?

### ISSUE THREAD

**Issue by zw-git** [tarantool/vshard#104]
I want to specify the range of bucketid on each replicaset，it's there a way to?

**Comment by Gerold103** [comment]
Thanks for your interest in vshard! No, unfortunately, vshard is an antipode of range sharding. If you want to store logically linked data in a single range, you can just store it in a single bucket - it will guarantee the data always be stored on a single replicaset.

**Comment by zw-git** [comment]
I want to store the data distributed， and rebanlance it via configure the range, mybe some especial bucketids take a lot of memory

**Comment by Gerold103** [comment]
Do you want manually manage your ranges? Literally configure them like `[start_bucket, end_bucket]` in config? I do not think it will help you if bucket sizes are misbalanced. For example, if a bucket `(start_bucket + end_bucket) / 2` is much bigger that others, you can not move out only it. Only split the entire range in two.

Do you know about replicaset weights feature? Maybe it could help you. When you see a replicaset stores too many data, you may decrease its weight, and the rebalancer will move some buckets out of it.
