### ISSUE TITLE
If necessary to  collect data after set the status to SENDING in function bucket_send?

### ISSUE THREAD

**Issue by zw-git** [tarantool/vshard#105]
in function https://github.com/tarantool/vshard/blob/master/vshard/storage/init.lua#L694
if some data changed between L715 and L719, is the collect data correct?

**Comment by Gerold103** [comment]
Data can not be changed between these lines. Look: a bucket can have several different states: `ACTIVE`, `PINNED`, `SENDING`, `SENT`, `RECEIVING`, `GARBAGE`. The bucket can accept non-readonly requests only in `ACTIVE` and `PINNED` states. If a one tries to execute a function with `write` mode on this bucket in another state - he gets `WRONG_BUCKET` error.

Common function call pipeline is the following: router does `router.call`, that calls `storage_call` function (line 1422 in storage/init.lua), that checks if a bucket is accessible for the required mode.

**Comment by zw-git** [comment]
@Gerold103 
I known above. I means that if there caused a yield in function bucket_collect_internal, and some other fiber change the space's data(the status have not changed to SENDING), and then come back to bucket_send, now changed the status to SENDING. so, i think the data it out of date. Is is possible?

select may cause a yield in vinyl(Implicit yields)
https://tarantool.io/en/doc/2.0/book/box/atomic.html#threads-fibers-and-yields


```
local data = bucket_collect_internal(bucket_id)  -- cause a yield, other changed space’s data
-- In a case of OOM or exception below the recovery fiber must
-- handle the 'sending' bucket.
M.buckets_to_recovery[bucket_id] = true
box.space._bucket:replace({bucket_id, consts.BUCKET.SENDING, destination})
```

If necessary to fix as follows?

```
-- In a case of OOM or exception below the recovery fiber must
-- handle the 'sending' bucket.
M.buckets_to_recovery[bucket_id] = true
box.space._bucket:replace({bucket_id, consts.BUCKET.SENDING, destination})
local data = bucket_collect_internal(bucket_id)  -- this statement
```

**Comment by Gerold103** [comment]
Oh, I understand now. No, it is still impossible, because bucket_collect_internal does not yield.

**Comment by zw-git** [comment]
https://tarantool.io/en/doc/2.0/book/box/atomic.html#threads-fibers-and-yields
there said that "In vinyl, not all data is in memory, and SELECT often incurs a disc I/O, and therefore yields, while a write may stall waiting for memory to free up, thus also causing a yield."
so, i'm confused.

**Comment by Gerold103** [comment]
Vshard does not work with Vinyl. It is pure memtx sharding. I plan to support Vinyl. Now it will not work not only because of the issue you found. The biggest problem - cross-engine transactions, that I need in Vshard, and that are not supported in Tarantool core.

**Comment by zw-git** [comment]
Oh, so that. Thanks a lot!
