### ISSUE TITLE
Delete bucket_id

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/vshard#120]
As I see a common application, which tables should be sharded, it consists of main table and child tables (and other stuff, which is not a subject in context of vshard).

Currently, there are 6 types of operations
1. insert into main table
2. update in main table
3. delete from main table
4. insert into child table
5. update in child table
6. delete from child table

What a sharded application need to has to perform those operations:
1-3 operations require main_object_pk, bucket_id
4-6 operations require child_object_pk, main_object_pk, bucket_id

`main_object_pk` is required for all operations at least to determine a bucket id.
`main_object_pk`/`child_object_pk` always sent as an argument to a function, to provide enough information on what to do.

Negative effects of bucket_id:
1. A bucket cannot be easily split up in two (vshard do not know pk->bucket_id mapping)
2. Justin Bibber's (huge_user) problem should be solved by creating AND PERSISTING additional pk->bucket_id mapping
3. bucket_id always can be calculated based on existing main_pk and just consumes space
4. Cannot optimize range query (by main_pk/child_pk)

My suggestion:
1. Automatically map main_pk -> unique_blob (or use user-provided function)
2. Shard/reshard/split ranges of unique_blobs automatically or with a help of user (range is a new vbucket)
3. Call stored procedures always providing a main_pk

This solves all the four issues.

Negative effects of the suggestion:
1. There are use cases where main_pk cannot or should not be stored in a child object.

Additional improvements:
1. As it is necessary to store main_pk in child tables (to find_its bucket_id), let's make a user to make a main_pk to be a part of a child_pk.

**Comment by racktear** [comment]
We don't always have a way to easily calculate bucket_id in related object. For example, when there are 2 related objects: a parent and a child, and the relation is set up by having a child_id field on a parent. Then there is no simple way to calculate bucket_id on a child, because it has no simple way of knowing what parent it belongs to

**Comment by Gerold103** [comment]
It has nothing to do with virtual buckets concept. It is rather an idea for a new sharding project.
