### ISSUE TITLE
Prohibit require('vshard')

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/vshard#137]
Prohibit `require('vshard')` and make a user require a `storage` or a `router` explicitly.

1. In 99% of cases, a user does not need both of them simultaneously.
2. A user has to remember to update router/storage in vshard by hand (`vshard.router = require(...`)

**Comment by racktear** [comment]
Alexey Khatskevich wrote:

> ну, короче, это тикет. Ты можешь написать там, что это говно идея

I think that it actually doesn't fix anything of importance, but breaks enough backwards compatibility without much reason.

**Comment by Gerold103** [comment]
@knazarov is right. Nothing to do here.
