### ISSUE TITLE
Move background lua gc to a separate module

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/vshard#138]
It looks like it is not a Vshard's responsibility to call `collectgarbage()`.

1. It seems to be redundant to call `collectgarbage()` by hand.
2. If it is a very common case for vshard users - `vshard.lua_garbagecollector` can be created.
3. It is not an easy task to implement garbage collection which minimizes latency. This should be implemented in a third-party module.

In @khatskevich 's opinion,  the only approach to make GC work more intensive (without patching jit) is to create a fiber, which calls `gc('step')` N times, and then `gc('fullgc')`. This would at least decrease GC pauses.

**Comment by Gerold103** [comment]
I agree. Lets do it as a separate fiber. This was my first implementation, but then @Mons said it is better to merge it into one of existing ones. However it looks ugly.
