### ISSUE TITLE
Prohibit vshard.router/storage.cfg from multiple fibers

### ISSUE THREAD

**Issue by Gerold103** [tarantool/vshard#140]
Lets do a simple lock like latch to prohibit multiple cfg as the same time.

**Comment by Gerold103** [comment]
@rave4life Please, do not close issues manually. It shall be done automatically as the commit is pushed into the master. I will review your commit and push it later.

**Comment by rave4life** [comment]
Okay, thanks. понедельник, 13 августа 2018г., 13:47 +03:00 от Vladislav Shpilevoy  notifications@github.com :

**Comment by tian-xi** [comment]
Build is failing on wheezy.
