### ISSUE TITLE
Test vshard.router reload over different vshard versions

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/vshard#141]
The same as #125 , but for the router module.

**Comment by Totktonada** [comment]
Can't it be an external machinery? Say, CI clones two versions, runs one workload on first version, runs another workload on second version. The test can be just Lua file (say, luatest test) and receive two paths to vshard sources via environment variables. So it will not be hard to run the same locally.

**Comment by Gerold103** [comment]
Perhaps it could be, don't know. The problem is that you can't restart the router. You need to reload it while it is running. Don't know if CI is of any help with that.
