### ISSUE TITLE
Run tests in parallel

### ISSUE THREAD

**Issue by Gerold103** [tarantool/vshard#174]
For that it is required to use zero port to bind, and deal with filtering out all the URIs from result files.

**Comment by Gerold103** [comment]
It is not as trivial as I thought - URIs are fixed in config. Possible solution - start tarantools on zero port, collect real ports, fill them into a config, use that config.

**Comment by Totktonada** [comment]
`use_unix_sockets` and `use_unix_sockets_iproto` options did help me for graphql (if you are about flaky fails). There is also an issue in test-run to fix that: https://github.com/tarantool/test-run/issues/141 (but nobody will do it, I think).

**Comment by Gerold103** [comment]
@Totktonada - not about flakiness. It is about a necessity to write all the URIs into configuration tables/files before Tarantool start. If do so, 1) parallel tests would collide on the same ports, 2) ports could be occupied already by not Tarantool. Probably unix sockets could help, if they are stored separately for each test in var/ dir. Are they? Then I could hardcode them into configs, and at the same time do not bump into collisions of different tests.

**Comment by Gerold103** [comment]
This https://github.com/tarantool/vshard/issues/371 will solve the problem. In the current diff-tests it is not realistic. Will need to rewrite them fully anyway for that.
