### ISSUE TITLE
Router should not start listen before it is ready to accept requests

### ISSUE THREAD

**Issue by Gerold103** [tarantool/vshard#194]
First `vshard.router.cfg` creates internal static router object, and configures it. During configuration it calls `box.cfg{listen = ..., ...}`, but before the configuration is actually finished. It leads to a problem, that router has already started listening, but is not ready to serve requests yet. The same problem exists for storage - box.cfg is called before _bucket is created.

**Comment by sergos** [comment]
https://github.com/tarantool/vshard/commit/5d935fc2783148b45aff584a60d039462488cd56 should resolve the storage part of the problem
