### ISSUE TITLE
Add possibility to remove replica from requests after several retries

### ISSUE THREAD

**Issue by shmel1k** [tarantool/vshard#198]
I have such kind of behavior.
I 'firewall' slave storage port in order to imitate packet-loss, e.g. `iptables -p tcp -A OUTPUT --sport STORAGE_PORT -j DROP`. I want disable slave from replicaset in order to prevent 'Timeout' errors.
This behavior can also be observed when I have some infinite loop in Tarantool's stored procedure without box.fiber.yield() inside.
Probably, we want to have such configuration parameters:
1. Network errors count: the count after which slave is disabled from replicaset.
2. Cooldown: the time after which slave is returned back to the replicaset.
3. Forgiveness timeout: the time after the last error when we forget about all errors occurred on the slave.

Can you please implement this feature?

**Comment by Gerold103** [comment]
A promising solution - lets add an option `retry_count` to `router.call`.

**Comment by sergos** [comment]
closing as resolved in #298
