### ISSUE TITLE
Error for bootstraped instances

### ISSUE THREAD

**Issue by v-izmalkov** [tarantool/vshard#204]
https://github.com/tarantool/doc/issues/925 
On the link above was original feedback gh-925 on bootstraped instances showing error in case of "make start" but still starting. 
The suggestion is to drop the error and just show a warning that bootstrap has been skipped.

**Comment by Gerold103** [comment]
This is not a good idea, because it might happen that a previous bootstrap was finished only partially. But ok, in 99% cases should not be a problem.

**Comment by Gerold103** [comment]
I will add an option to bootstrap which would allow to ignore that particular error.
