### ISSUE TITLE
Why bucket_id can be absent from working router?

### ISSUE THREAD

**Issue by makorne** [tarantool/vshard#216]
Started cartridge app, all healthy and working.

`router | 2020-02-26 16:36:09.090 [26409] main/123/applier/admin@localhost:3331 C> leaving orphan mode
router | 2020-02-26 16:36:09.092 [26409] main/124/localhost:3332 (net.box) I> connected to localhost:3332
router | 2020-02-26 16:36:09.095 [26409] main/125/localhost:3334 (net.box) I> connected to localhost:3334
router | 2020-02-26 16:36:09.095 [26409] main/126/lua I> failover_f has been started
router | 2020-02-26 16:36:09.095 [26409] main/126/lua I> New replica localhost:3332(admin@localhost:3332) for replicaset(uuid="3b5c7068-0590-4bff-8f9f-b7867153e8bb", master=localhost:3332(admin@localhost:3332))
router | 2020-02-26 16:36:09.095 [26409] main/126/lua I> New replica localhost:3334(admin@localhost:3334) for replicaset(uuid="dc9a608e-6298-4c9c-86f0-d6d2c6f34b2a", master=localhost:3334(admin@localhost:3334))
router | 2020-02-26 16:36:09.095 [26409] main/126/lua I> All replicas are ok
router | 2020-02-26 16:36:09.095 [26409] main/126/lua I> Failovering step is finished. Schedule next after 1.000000 seconds
router | 2020-02-26 16:36:09.095 [26409] main/127/lua I> discovery_f has been started
router | 2020-02-26 16:36:09.096 [26409] main/119/lua I> Config applied
router | 2020-02-26 16:36:09.103 [26409] main/127/vshard.discovery._static_router I> Updated replicaset(uuid="3b5c7068-0590-4bff-8f9f-b7867153e8bb", master=localhost:3332(admin@localhost:3332)) buckets: was 0, became 15000
s2-master | 2020-02-26 16:36:09.239 [26411] main/119/lua C> leaving orphan mode
s2-master | 2020-02-26 16:36:09.239 [26411] main/119/lua I> set 'replication_connect_quorum' configuration option to 0
s2-master | 2020-02-26 16:36:09.239 [26411] main/119/lua I> set 'replication_connect_timeout' configuration option to 1e-06
s2-master | 2020-02-26 16:36:09.239 [26411] main/119/lua I> connecting to 1 replicas
s2-master | 2020-02-26 16:36:09.239 [26411] main/119/lua C> failed to connect to 1 out of 1 replicas
s2-master | 2020-02-26 16:36:09.239 [26411] main/119/lua C> leaving orphan mode
s2-master | 2020-02-26 16:36:09.239 [26411] main/119/lua I> set 'replication' configuration option to ["admin@localhost:3334"]
s2-master | 2020-02-26 16:36:09.239 [26411] main/119/lua I> set 'read_only' configuration option to false
s2-master | 2020-02-26 16:36:09.239 [26411] main/119/lua I> Reconfiguring vshard.storage...
s2-master | 2020-02-26 16:36:09.239 [26411] main/119/lua I> Starting configuration of replica 2ea5c52c-1443-467d-9e8e-ff25e89df78f
s2-master | 2020-02-26 16:36:09.239 [26411] main/119/lua I> I am master
s2-master | 2020-02-26 16:36:09.239 [26411] main/119/lua I> Taking on replicaset master role...
s2-master | 2020-02-26 16:36:09.239 [26411] main/119/lua I> Box has been configured
s2-master | 2020-02-26 16:36:09.240 [26411] main/124/lua I> gc_bucket_f has been started
s2-master | 2020-02-26 16:36:09.240 [26411] main/125/lua I> recovery_f has been started
s2-master | 2020-02-26 16:36:09.240 [26411] main/119/lua I> Took on replicaset master role
s2-master | 2020-02-26 16:36:09.260 [26411] main/123/applier/admin@localhost:3334 I> remote master 2ea5c52c-1443-467d-9e8e-ff25e89df78f at 127.0.0.1:3334 running Tarantool 2.3.1
s2-master | 2020-02-26 16:36:09.261 [26411] main/123/applier/admin@localhost:3334 C> leaving orphan mode
s2-master | 2020-02-26 16:36:09.282 [26411] main/119/lua I> Config applied
router | 2020-02-26 16:36:10.095 [26409] main/126/vshard.failover._static_router I> All replicas are ok
s1-master | 2020-02-26 16:36:18.292 [26418] main/124/vshard.rebalancer I> The cluster is balanced ok. Schedule next rebalancing after 3600.000000 seconds
router | 2020-02-26 16:36:19.112 [26409] main/127/vshard.discovery._static_router I> Updated replicaset(uuid="dc9a608e-6298-4c9c-86f0-d6d2c6f34b2a", master=localhost:3334(admin@localhost:3334)) buckets: was 0, became 15000`

****But in some cases vshard.router.bucket_id is absent. 
Below  is router dump for such cases:****

`{ ["error"] = { ["make"] = function: 0x40ad6cc0,["code"] = { ["NON_EMPTY"] = 10,["UNREACHABLE_MASTER"] = 11,["SUBOPTIMAL_REPLICA"] = 17,["REPLICASET_IS_LOCKED"] = 19,
["LOW_REDUNDANCY"] = 15,["NO_ROUTE_TO_BUCKET"] = 9,["NON_MASTER"] = 2,["MOVE_TO_SELF"] = 5,["HIGH_REPLICATION_LAG"] = 13,["UNKNOWN_BUCKETS"] = 18,["WRONG_BUCKET"] = 1,
["TRANSFER_IS_IN_PROGRESS"] = 7,["NO_SUCH_REPLICASET"] = 4,["BUCKET_IS_LOCKED"] = 22,["INVALID_REBALANCING"] = 16,["OBJECT_IS_OUTDATED"] = 20,["UNREACHABLE_REPLICASET"] = 8,
["UNREACHABLE_REPLICA"] = 14,["OUT_OF_SYNC"] = 12,["ROUTER_ALREADY_EXISTS"] = 21,["BUCKET_ALREADY_EXISTS"] = 3,["MISSING_MASTER"] = 6,} ,["vshard"] = function: 0x40ad72b8,
["box"] = function: 0x40ed9bb8,["alert"] = function: 0x40ad6d28,} ,["consts"] = { ["REPLICATION_THRESHOLD_FAIL"] = 10,["DEFAULT_FAILOVER_PING_TIMEOUT"] = 5,
["DEFAULT_REBALANCER_DISBALANCE_THRESHOLD"] = 1,["CALL_TIMEOUT_MIN"] = 0.5,["DEFAULT_BUCKET_COUNT"] = 3000,["DEFAULT_COLLECT_BUCKET_GARBAGE_INTERVAL"] = 0.5,[
"STATUS"] = { ["ORANGE"] = 2,["YELLOW"] = 1,["RED"] = 3,["GREEN"] = 0,} ,["REBALANCER_CHUNK_TIMEOUT"] = 300,["REBALANCER_WORK_INTERVAL"] = 10,["RECONNECT_TIMEOUT"] = 0.5,
["COLLECT_LUA_GARBAGE_INTERVAL"] = 100,["FAILOVER_UP_TIMEOUT"] = 5,["RECOVERY_INTERVAL"] = 5,["DEFAULT_SYNC_TIMEOUT"] = 1,["REPLICATION_THRESHOLD_HARD"] = 5,
["BUCKET_SENT_GARBAGE_DELAY"] = 0.5,["BUCKET"] = { ["ACTIVE"] = active,["RECEIVING"] = receiving,["SENT"] = sent,["PINNED"] = pinned,["GARBAGE"] = garbage,["SENDING"] = sending,} ,
["REPLICATION_THRESHOLD_SOFT"] = 1,["DISCOVERY_INTERVAL"] = 10,["CALL_TIMEOUT_MAX"] = 64,["FAILOVER_DOWN_TIMEOUT"] = 1,["DEFAULT_REBALANCER_MAX_RECEIVING"] = 100,["REBALANCER_IDLE_INTERVAL"] = 3600,
["BUCKET_CHUNK_SIZE"] = 1000,} ,
["router"] = { ["cfg"] = function: 0x405ac268,["module_version"] = function: 0x405a9d60,["internal"] = { ["routers"] = { } ,
["collect_lua_garbage_cnt"] = 0,["errinj"] = { ["ERRINJ_LONG_DISCOVERY"] = false,["ERRINJ_CFG"] = false,["ERRINJ_RELOAD"] = false,["ERRINJ_FAILOVER_CHANGE_CFG"] = false,} ,
["router_mt"] = { ["__index"] = { ["callro"] = function: 0x405ab5e0,["call"] = function: 0x405ab6c8,["callre"] = function: 0x405abc10,["discovery_wakeup"] = function: 0x405ac5d8,
["bucket_discovery"] = function: 0x405abda8,["bootstrap"] = function: 0x405abcc0,["callbre"] = function: 0x405abf80,["bucket_count"] = function: 0x405ac030,
["info"] = function: 0x405ac0e0,["sync"] = function: 0x405abe58,["bucket_id"] = function: 0x405ac318,["route"] = function: 0x405ac3c8,["callbro"] = function: 0x405ac478,
["routeall"] = function: 0x405ac528,["buckets_info"] = function: 0x405ac738,["callrw"] = function: 0x405ac688,["cfg"] = function: 0x405ab690,} ,} ,
["failover_f"] = function: 0x405aab48,["discovery_f"] = function: 0x405aa408,["module_version"] = 0,} ,["new"] = function: 0x405ac1f8,} ,
["storage"] = { ["rebalancer_disable"] = function: 0x40b73f30,["is_locked"] = function: 0x40b72e78,[
"bucket_unrefrw"] = function: 0x40b733b0,["bucket_ref"] = function: 0x40b733d8,["rebalancer_wakeup"] = function: 0x40b73f10,["bucket_stat"] = function: 0x40b734a8,
["on_master_disable"] = function: 0x40b73008,["bucket_unpin"] = function: 0x40b73888,["bucket_refrw"] = function: 0x40b73380,["info"] = function: 0x40b74200,
["rebalancer_request_state"] = function: 0x40b73ee8,["internal"] = { ["bucket_refs"] = { } ,["_on_master_disable"] = { ["name"] = _on_master_disable,} ,["recovery_f"] = function: 0x40b73198,[
"is_rebalancer_active"] = true,["reload_version"] = 1,["rebalancer_f"] = function: 0x40b73e28,["rebalancer_max_receiving"] = 0,["rebalancer_transfering_buckets"] = { } ,
["errinj"] = { ["ERRINJ_RECEIVE_PARTIALLY"] = false,["ERRINJ_LONG_RECEIVE"] = false,["ERRINJ_LAST_RECEIVE_DELAY"] = false,["ERRINJ_RELOAD"] = false,["ERRINJ_CFG"] = false,["ERRINJ_CFG_DELAY"] = false,
["ERRINJ_BUCKET_FIND_GARBAGE_DELAY"] = false,} ,["bucket_generation"] = 0,["sync_timeout"] = 1,["_on_master_enable"] = { ["name"] = _on_master_enable,} ,["module_version"] = 0,
["total_bucket_count"] = 0,["rebalancer_calculate_metrics"] = function: 0x40b73ca0,["rebalancer_build_routes"] = function: 0x40b73ce0,["gc_bucket_step_by_type"] = function: 0x40b73920,["gc_bucket_f"] = function: 0x40b739b8,
["rebalancer_disbalance_threshold"] = 0,["cached_find_sharded_spaces"] = function: 0x40b735e8,["bucket_rw_lock_is_ready_cond"] = cond,} ,["bucket_send"] = function: 0x40b73808,["buckets_discovery"] = function: 0x40b73698,
["garbage_collector_wakeup"] = function: 0x40b73c38,["bucket_delete_garbage"] = function: 0x40b73c58,["bucket_refro"] = function: 0x40b732e8,["rebalancer_enable"] = function: 0x40b73f50,
["bucket_force_create"] = function: 0x40b734f0,["cfg"] = function: 0x40b74b68,["bucket_recv"] = function: 0x40b735a0,["module_version"] = function: 0x40b74bc8,["buckets_info"] = function: 0x40b741e0,
["recovery_wakeup"] = function: 0x40b73208,["bucket_collect"] = function: 0x40b73650,["rebalancer_apply_routes"] = function: 0x40b73d70,["sharded_spaces"] = function: 0x40b74ba8,
["sync"] = function: 0x40b73248,["on_master_enable"] = function: 0x40b73050,["bucket_unref"] = function: 0x40b73440,["bucket_unrefro"] = function: 0x40b73358,["bucket_force_drop"] = function: 0x40b73530,
["bucket_pin"] = function: 0x40b73860,["rebalancing_is_in_progress"] = function: 0x40b73078,["call"] = function: 0x40b73f70,["buckets_count"] = function: 0x40b741c0,} ,}`

Looks like something does not get initialized in app code.

What is mandatory for this function?

**Comment by Gerold103** [comment]
vshard.router.bucket_id() is created after first vshard.router.cfg().

**Comment by makorne** [comment]
Ok, thank you!

And what about this message in log when cartridge app is starting:

`s1-master | 2020-02-27 11:46:25.800 [8290] main/124/vshard.rebalancer replicaset.lua:244 E> Exception during calling 'vshard.storage.rebalancer_request_state' on 'localhost:3334(admin@localhost:3334)': Procedure 'vshard.storage.rebalancer_request_state' is not defined
`

Is that normal? 
All looks work good.

**Comment by Gerold103** [comment]
Yeah, that may happen, if rebalancer storage was bootstrapped earlier than others, and it tried to connect to them. Perhaps I could make the error message more informative.
