### ISSUE TITLE
Wrong behavior with replicaset_object:callre

### ISSUE THREAD

**Issue by ArtDu** [tarantool/vshard#269]
There are 3 storages in 3 zones and 1 router in zone 1. We have set zones for each node. Master storage in zone 2, replicas in zone 1 and 3. The router is in zone 1. We have weights for the zones that we place.
```
 0  10   1
10   0  12
 1  12   0 
```
From this it follows that for a router from zone 1 the weight goes to zone 2 = 10, and in zone 3 = 1. When you call replicaset_object:callre, the router must go to the storage with the lowest zone weight, i.e. in storage with zone 3.

We look where the router goes from the 1 zone, it goes to zone 2, where the master of our replicaset is.

the repro was made on a cartridge framework: https://github.com/tarantool/cartridge/pull/1315

**Comment by Gerold103** [comment]
From the code I see that it should work according to the zone. I will check it, but if you want to speed it up, please, provide a test on bare vshard. Cartridge is not a part of vshard, so I can't be sure you don't have a bug there.

**Comment by kyukhin** [comment]
Looks like a bug in cartrige, not in vshard https://github.com/tarantool/cartridge/pull/1315#issuecomment-800608827

**Comment by sharonovd** [comment]
Actually not, not in cartridge. 
In any case, vshard works as expected.
