### ISSUE TITLE
Allow to choose where to start rebalancer, via a config option

### ISSUE THREAD

**Issue by Gerold103** [tarantool/vshard#278]
Otherwise it is hard to find it to read the logs.

**Comment by sharonovd** [comment]
I'd prefer to get this info from vshard.cfg more easily. Auto-choose is better than manual selection as long as I am able to quickly navigate to the node.

**Comment by sharonovd** [comment]
E. g. 
> vshard.localet_rebalancer()
 - 192.168.11.15:3301

**Comment by Gerold103** [comment]
Done in https://github.com/tarantool/vshard/commit/d62497302c531bc4159081eba095a408569ad626 and https://github.com/tarantool/vshard/commit/9fda3546ded3f74fa03dda371a984986e2b367d1.
