### ISSUE TITLE
attempt to index field 'this_replicaset' (a nil value)

### ISSUE THREAD

**Issue by olegrok** [tarantool/vshard#286]
vshard 0.1.17

I had following error:
> {"class_name":"funcall_error","err":"...jects\/tdg\/.rocks\/share\/tarantool\/vshard\/storage\/init.lua:889: attempt to index field 'this_replicaset' (a nil value)","stack":"stack traceback:\n\t...jects\/tdg\/.rocks\/share\/tarantool\/vshard\/storage\/init.lua:973: in function 'bucket_ref'\n\t...jects\/tdg\/.rocks\/share\/tarantool\/vshard\/storage\/init.lua:2405: in function <...jects\/tdg\/.rocks\/share\/tarantool\/vshard\/storage\/init.lua:2404>\n\t[C]: in function 'xpcall'\n\t...s\/o.babin\/Projects\/tdg\/.rocks\/share\/tarantool\/errors.lua:145: in function <...s\/o.babin\/Projects\/tdg\/.rocks\/share\/tarantool\/errors.lua:139>\n\t[C]: at 0x01091b3940","str":"funcall_error: ...jects\/tdg\/.rocks\/share\/tarantool\/vshard\/storage\/init.lua:889: attempt to index field 'this_replicaset' (a nil value)"}

Probably it's related to replication conflict that I also got.
Complete log: [test.log](https://github.com/tarantool/vshard/files/6732609/test.log) (it's Cartridge application that uses vshard). It happened in my tests only once (test checks that Cartridge failover correctly works).

**Comment by Gerold103** [comment]
I think the reason is the same as in #123. Will be fixed together with it probably.
