### ISSUE TITLE
How transfer function box.execute() in vshard.callro() function ?

### ISSUE THREAD

**Issue by Bl4ugrane** [tarantool/vshard#289]
How i can transfer function box.execute([[SELECT * FROM TABLE;]]) used vshard.callro()?

Example:
shards = vshard.router.routeall()
    for uid, replica in pairs(shards) do
        local set = replica:callro('box.execute([[SELECT * FROM TABLE;]])', { {}, {} })
    end

**Comment by olegrok** [comment]
Simplified example

```
tarantool> rs:callro('box.execute', {'SELECT ?', {1}})
---
- {'metadata': [{'name': 'COLUMN_1', 'type': 'integer'}], 'rows': [[1]]}
- null
- null
...
```

**Comment by Bl4ugrane** [comment]
Thanks
