### ISSUE TITLE
Error on bootstrap

### ISSUE THREAD

**Issue by no1seman** [tarantool/vshard#291]
On 0.1.18 when bootstap cluster with cartridge-cli got the following error:
2021-08-11 19:16:40.482 [64441] main/133/http/127.0.0.1:44012 graphql.lua:313 E> Graphql execution failed: ...-cartridge/.rocks/share/tarantool/vshard/router/init.lua:1325: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
	...-cartridge/.rocks/share/tarantool/vshard/router/init.lua:1325: in function 'info'
	...dge/.rocks/share/tarantool/cartridge/lua-api/boxinfo.lua:52: in function 'get_info'
	...e/.rocks/share/tarantool/cartridge/webui/gql-boxinfo.lua:330: in function 'defaultResolver'
	...-cartridge/.rocks/share/tarantool/graphql/execute.lua:303: in function 'getFieldEntry'
	...-cartridge/.rocks/share/tarantool/graphql/execute.lua:322: in function 'evaluateSelections'
	...-cartridge/.rocks/share/tarantool/graphql/execute.lua:224: in function 'completeValue'
	...-cartridge/.rocks/share/tarantool/graphql/execute.lua:213: in function 'completeValue'
	...-cartridge/.rocks/share/tarantool/graphql/execute.lua:309: in function 'getFieldEntry'
	...-cartridge/.rocks/share/tarantool/graphql/execute.lua:322: in function <...-cartridge/.rocks/share/tarantool/graphql/execute.lua:314>
	...
	...k-cartridge/.rocks/share/tarantool/cartridge/graphql.lua:300: in function <...k-cartridge/.rocks/share/tarantool/cartridge/graphql.lua:226>
	[C]: in function 'xpcall'
	...-cartridge/.rocks/share/tarantool/errors.lua:145: in function 'pcall'
	...-cartridge/.rocks/share/tarantool/cartridge/graphql.lua:335: in function 'sub'
	...-cartridge/.rocks/share/tarantool/http/server.lua:658: in function <...l-cartridge/.rocks/share/tarantool/http/server.lua:636>
	[C]: in function 'pcall'
	...-cartridge/.rocks/share/tarantool/http/server.lua:736: in function 'process_client'
	...-cartridge/.rocks/share/tarantool/http/server.lua:1199: in function <...-cartridge/.rocks/share/tarantool/http/server.lua:1198>
	[C]: in function 'pcall'
	builtin/socket.lua:1081: in function <builtin/socket.lua:1079>

**Comment by Gerold103** [comment]
It is most likely happening because you are trying to get info before the router finished its configuration. I will probably try to raise a proper error for this.

**Comment by no1seman** [comment]
Yes, but this happens when reboting replicas (cartridge stop && catridge start) with Cartridge WebUI loaded, so cartridge WebUI polls backend and periodically described shit happens.
