### ISSUE TITLE
replicaset:stream()

### ISSUE THREAD

**Issue by olegrok** [tarantool/vshard#292]
I think after https://github.com/tarantool/tarantool/issues/5860 vshard should provide a way to open streams to replicaset instances.

We need something like `replicaset:stream_rw()`, `replicaset:stream_bre`, ... that opens a stream to some master/replica.

**Comment by NeraverinTarantool** [comment]
@olegrok can you describe specific use case for this feature?

**Comment by olegrok** [comment]
Probably I expected to have an ability to create a read view on specific instance.
Just get a stream when MVCC is enabled and then perform some read queries on that instance. (Initially I planned to use it for TDG map-reduces).

Currently I'm not sure that it's a good idea. It's quite tricky to perform fullscans or huge queries in transactions (due to memory consumption)... So, fair read views are available only in EE. See https://t.me/tarantoolru/177373
