### ISSUE TITLE
Support 'raw args' feature from the latest Tarantool to avoid args decoding on router

### ISSUE THREAD

**Issue by Gerold103** [tarantool/vshard#312]
The newest Tarantool version has a new function setting `takes_raw_args`. Instance can create such function in `_func` and it will take arguments as a raw MessagePack buffer. The function then can decode some first arguments and leave the others not decoded. For instance, to forward them further to another instance.

Also netbox now supports `return_raw` option - works the same. Result of the remote call is a raw MessagePack buffer. Not decoded into Lua values.

These options together should help to reduce pressure on the router when it is used as a proxy. Router would need to offer a function like `vshard.router.callraw()`. It would take a MessagePack buffer with the same arguments encoded as `vshard.router.call()` and return result also as a MessagePack buffer (using `return_raw` netbox option when talks to the storage).

In order to use it the user would need to register it in `_func` with `takes_raw_args` and call it from clients. Router can't do that itself, because it is not supposed to depend on any local spaces.

**Comment by Serpentian** [comment]
@Gerold103. why the issue is marked as closed, when we didn't implement the second half of the issue?

> These options together should help to reduce pressure on the router when it is used as a proxy. Router would need to offer a function like vshard.router.callraw(). It would take a MessagePack buffer with the same arguments encoded as vshard.router.call() and return result also as a MessagePack buffer (using return_raw netbox option when talks to the storage).

Should we create a new issue or reopen this one? The issue was planned to the next release, that's why I'm asking

**Comment by Gerold103** [comment]
Tbh, I don't remember exactly why. But I can imagine the following:
- The heaviest useless Lua decoding was for the data received from the storage. To avoid that the regular `router.call()` and `map_call()` support `return_raw = true` option. The caller of `router.call` functions can just return their msgpack result into the network.
- The idea of having the router itself a function taking raw arguments (i.e. an msgpack object with values `[bucket_id, shard_opts, func, args, opts]`) was probably not done, because it is unlikely to be needed (arguments **to** the storage are small, the result **from** the storage is big), and for other people it is trivial to add on their own. Users can do it themselves. Just register a function `callraw(msgpack)`, decode its first 3 arguments (`bucket_id, shard_opts, func`), skip the fourth one (`args`), and decode the last one (`opts`). Pass it all to `router.call()`. The router won't touch the args, so they can be in any format, including being an msgpack object.
