### ISSUE TITLE
Support instance/replicaset/cluster names instead of UUIDs in the configuration

### ISSUE THREAD

**Issue by Totktonada** [tarantool/vshard#426]
See #407 and https://github.com/tarantool/tarantool/pull/8289.

The key difference from the configuration using UUIDs is that instance/replicaset/cluster names are known at the configuration stage.

It is especially important in case of a cluster configuration introduced in https://github.com/tarantool/tarantool/issues/8724.

There is a workaround: use a hash function to generate UUIDs from names. However, it complicates upgrading from old snapshots, where there are no persistent instance/replicaset/cluster names.

I would appreciate hints about possible pitfalls on the road. What else we need to do except just passing the parameters down to `box.cfg()`?

**Comment by Gerold103** [comment]
There are no pitfalls. It just needs to be done and shouldn't be even complicated.
