### ISSUE TITLE
Router sends requests to dead instances

### ISSUE THREAD

**Issue by Serpentian** [tarantool/vshard#480]
This is the critical issue and must be fixed as soon as possible. When instance is dead for some reason (e.g. tx thread is 100% loaded, `while true do end` on instance), vshard continues to send requests to it, which fails with TimeOut error. This happens, as connection doesn't die, when tx thread is busy (`wait_connected` returns `true`). Manually disabling the instance always fixes the problem, erroneous requests disappear. 

https://github.com/tarantool/vshard/blob/2211be294d222cc2103fd3c410c7f084e4eb9ea1/vshard/replicaset.lua#L790-L796

Currently router requests fail way too often, which affects users in mission critical projects. Vshard must try to minimize the number of `timed out` errors (and probably any other errors). We should consider the following approaches:
 * https://github.com/tarantool/vshard/issues/483
 * https://github.com/tarantool/vshard/issues/484
 
As a follow up we may introduce the following ticket, but only if smb asks, since it requires user intervention and writing triggers:

* https://github.com/tarantool/vshard/issues/485

**Comment by sergepetrenko** [comment]
There's also a ticket to make `net.box` track connection state: https://github.com/tarantool/tarantool/issues/9563

But if we choose to fix that ticket, it'll only go to new tarantool releases, leaving vshard installations on old tarantool versions   still affected by this bug.

So I vote for fixing it separately in vshard
