### ISSUE TITLE
`map_callrw` may be inconsistent

### ISSUE THREAD

**Issue by Serpentian** [tarantool/vshard#504]
Consistency of `map_callrw` guarantees, that the function will be executed on every master:

> The given function is called on masters in the cluster with a guarantee that in case of success it was executed with all buckets being accessible for reads and writes.

However, this is not always true.  Imagine the following situation: master successfully sets refs (which will be removed on timeout) on all storages, but it executes Map stage too late, when some of the refs already expired. This way the function will be executed on some instances and this is not the guarantees we want.

Reported by @Gerold103 

---

There's no simple solution for this, AFAICS. It's the problem of how 2PC works, we either may end up in the inconsistent state when timeouts are used (described in the situation above) or may leave rebalancing blocked forever, if router fails right after Ref stage and timeouts are not used. 

Probably, the only available solution here, is using consensus algorithm on the group of shard master's. But this doesn't sound realistic in terms of how much time is needed to implement this. Moreover, the problem is hard to reproduce: router must be 100% loaded for timeout to fire later than timeout on storages.

**Comment by Gerold103** [comment]
This isn't a bug, really. It can never be guaranteed in a distributed system. Even if you take 2PC - you can never promise the transaction ends. And you can still get partial write (on some instances it is committed, on some it still isn't). In case of `map_callrw()` we do only guarantee, that if the function didn't fail, it means it was executed everywhere. But if it fails, it is legal that it might have been already executed on some replicasets.

`map_callrw()` can be in theory used for distributed txns, but it isn't itself one.

**Comment by Serpentian** [comment]
Since this is not possible to implement, we can close it
