### ISSUE TITLE
Pure-proxy mode

### ISSUE THREAD

**Issue by kostja** [tarantool/vshard#60]
We need a mode in vshard which makes it a pure master/slave automatic failover proxy. I.e. makes sure that it can transparently forward pretty much anything in the binary protocol to the currently active master, and fail over to another master when the active master is not available. 
This is a feature request that community has been asking for for ages, and is reflected in https://github.com/tarantool/tarantool/issues/2625

**Comment by Gerold103** [comment]
It is done already. See failover_f function in router/init.lua.

**Comment by Gerold103** [comment]
Since this is reflected in https://github.com/tarantool/tarantool/issues/2625, I suggest it be done there. It makes little sense to expose such module as a part of vshard, if it won't depend on anything in vshard (buckets, `vshard.storage.*` functions).
